version: 2.1
orbs:
  node: circleci/node@4.7
jobs:
  build:
    docker:
      - image: cimg/node:18.16.0
    steps:
      - checkout
      - run: npm install
      - run: git log --oneline --decorate > public/changelog.txt
      - run: npm test
      - run: npm run build
workflows:
  version: 2
  deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
