version: 2.1
orbs:
  node: circleci/node@4.7
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: npm install
      - run: git log --oneline --decorate > public/changelog.txt
      - run: npm run circleci-build
      - run: npm test
workflows:
  version: 2
  deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
