###
POST http://localhost:8080/api/login/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded

username=zdzichu
###

GET http://localhost:8080/api/login HTTP/1.1
###

POST http://localhost:8080/api/login/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded

username=zdzichu
###

GET http://localhost:8080/ HTTP/1.1
###

GET http://localhost:8080/api/ HTTP/1.1
###

GET http://localhost:8080/api/status HTTP/1.1
###

GET http://localhost:8080/api/status/server HTTP/1.1
###

GET http://localhost:8080/api/status/mongodb HTTP/1.1
###
